### ISSUE TITLE
hexo meting吗？

### ISSUE THREAD

**Issue by greenhandzdl** [Candinya/aplayer-simple-backend#1]
里面说要求安装meeting，但是比较新的包里面好像有meting，那么meting能不能满足。
emmm，还有就是playlist是填id还是填超链

**Comment by Candinya** [comment]
这个只是一个用于连接aplayer和meting的PHP后端，与hexo本体无关，请分开部署。
而kratos-rebirth主题的aplayer设置段中需要填入详细的歌单文件地址（可以是静态的JSON文件或是使用这个PHP脚本动态获取的歌单，调用的方式可以参见ReadMe.md），单填入一串歌单的ID是无效的（因为主题和播放器并未集成前端跨域请求及解码功能）
以及请注意，由于meting使用的是网页版的网易云音乐API，因而对网易云音乐现在有歌单爬取的歌曲数量限制，可能会存在歌单不完整的情况，请酌情考虑使用。

**Comment by greenhandzdl** [comment]
那么pages允许php吗？emmm

**Comment by Candinya** [comment]
不支持。
GitHub Pages是静态文件服务。

**Comment by greenhandzdl** [comment]
话说直接在首页加meting不行吗？emmm，不然每次生成时都要改html有点点累

**Comment by Candinya** [comment]
meting我记得是动态的脚本，需要后端伺服器才能运行，即使使用那些api的使用的也都是他人搭建的后端吧，如果有纯前端静态的话可以考虑再参考整合一下
以及并不需要改html，如果使用后端的话您将播放器的歌单文件参数填写至主题配置文件的对应项即可。

**Comment by greenhandzdl** [comment]
我发现好像不一定需要动态
![Screenshot_2020-10-17-20-14-09-60](https://user-images.githubusercontent.com/61241103/96336941-959ab080-10b5-11eb-8313-cd0ec39588ec.png)
因为我就是直接填网链，然后成了
环境是pages
